name: Install on macOS

on:
  - push
  - pull_request

jobs:
  install:
    runs-on: macos-latest

    strategy:
      matrix:
        shell:
          - bash
          - dash
          - ksh
          - sh
          - zsh
        script:
          - install.sh
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Install shell
        run: brew install ${{ matrix.shell }}
        if: ${{ matrix.shell == 'ksh' || matrix.shell == 'dash' }}
      - name: Run installation script
        run: SHELL="$(which ${{ matrix.shell }})" ${{ matrix.shell }} ${{ matrix.script }}
