name: Shellcheck

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        shell:
          - sh
          - dash
          - bash
          - ksh
        script:
          - beta-install.sh
          - install.sh

    steps:
      - uses: actions/checkout@v2
      - name: Shellcheck
        run: shellcheck -s ${{ matrix.shell }} ${{ matrix.script }}
