name: Shellcheck

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        shell:
          - bash
          - dash
          - ksh
          - sh

    steps:
      - uses: actions/checkout@v2
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        env:
          SHELLCHECK_OPTS: -s ${{ matrix.shell }}
