name: Shellcheck

on:
  push:
    branches: [main, umireon-shellcheck]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Shellcheck
        run: shellcheck beta-install.sh
